spring:
  profiles: alpha
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33091/daddyprogrammer?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 159357
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    showSql: true
    generate-ddl: false
  url:
    base: http://alpha.daddyprogrammer.org
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: warn
    com.rest.api: info
  path: /home/ec2-user/api/log
  file:
    max-history: 7